# Generated by Django 4.2.5 on 2023-09-29 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_size_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={},
        ),
    ]
